name: deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: '43 5 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 24.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
